name: Build Fyne App - Windows

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.x

    - name: Build Fyne App - Windows
      run: go build cmd/fyne-app/main.go

    - name: Package Fyne App - Widnows
      run: |
        cd cmd/fyne-app
        go mod download
        fyne package -os windows -icon ../../assets/Icon.png -name PartsPal

    - name: Save build artifact
      run: |
        mkdir build
        mv main.exe build/
        mv cmd/fyne-app/PartsPal.app build/
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout -b fyne-build-windows
        git add -f build/main.exe
        git commit -m "Add Fyne app build for Windows"
        git push --force origin fyne-build-windows
